### ISSUE TITLE
Last modified info in branches view

### ISSUE THREAD

**Issue by juanfcocontreras** [gitbucket/gitbucket#1183]
In the branches view (when you click on "Branches" in the sidebar), last modified version is the same in every branch: the latest one. I think this is broken because you want to see the latest version per branch.

This happened to me in previous versions and is still present in the 4.0.

**Comment by takezoe** [comment]
@juanfcocontreras Hmm... I couldn't reproduce in my environment. Could you attach the pictures of your branch list in GitBucket and the other Git front-end which can be confirmed the last modified date on GitBucket and actual?

**Comment by takezoe** [comment]
Is this issue same as #1167?

**Comment by takezoe** [comment]
@juanfcocontreras If invalid branch is only default branch, I think your issue id same as #1167 and it's resolved in 4.1. But if all your branches are showing invalid date, I need more information as mentioned above.

**Comment by juanfcocontreras** [comment]
Sorry, confirmed, it's the same issue. I think I've already seen it, but when I searched yesterday I couldn't find it. I thought it was marked to do it in 4.0 version, so when I check that it was still present, I send the issue.

Sorry for the inconvenience. Please, close this one.

**Comment by takezoe** [comment]
@juanfcocontreras Thanks for your confirmation. #1167 is already fixed and released in 4.1.
