### ISSUE TITLE
New Error in 4.35.0 when creating webhook

### ISSUE THREAD

**Issue by solvingj** [gitbucket/gitbucket#2618]
Using 4.35.0 from dockerhub: 
`FROM gitbucket/gitbucket:4.35.0`

When creating a webhook with curl command, I get a new error in the Gitbucket logs.  (command and error shown below). 

Furthermore, the GUI does show that the hook has been created, but hooks don't seem to be sent on the branch `Create` event anymore. 

Of note, I saw this comment in the 4.35.1 release notes:

> Fix database migration issue which happens if webhook is configured

In my case, I pulled down the fresh docker image from scratch so there was no webhook already configured, so it might not be related.  Still, the error clearly indicates an issue with the database schema related to webhooks, so I'm going to guess there's some relation.

```
curl --user "root:root" \
-X POST "http://gitbucket/api/v3/repos/root/settings/hooks" \
-d '{"name":"jenkins","config":{"url":"'"http://jenkins:8080/github-webhook/"'"},"events":["create", "push", "pull_request"]}'
```

```
20:15:16.381 [qtp648129364-12] ERROR g.core.controller.ApiController - Catch unhandled error in request: Request(POST //gitbucket/api/v3/repos/root/scripts/hooks)@53bd1673
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.IDX_WEB_HOOK_1_INDEX_D ON PUBLIC.WEB_HOOK(USER_NAME, REPOSITORY_NAME, URL) VALUES 1"; SQL statement:
insert into "WEB_HOOK" ("USER_NAME","REPOSITORY_NAME","URL","CTYPE","TOKEN") values (?,?,?,?,?) [23505-199]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
at org.h2.message.DbException.get(DbException.java:205)
at org.h2.message.DbException.get(DbException.java:181)
at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:220)
at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:196)
at org.h2.mvstore.db.MVTable.addRow(MVTable.java:546)
at org.h2.command.dml.Insert.insertRows(Insert.java:180)
at org.h2.command.dml.Insert.update(Insert.java:132)
at org.h2.command.CommandContainer.update(CommandContainer.java:133)
at org.h2.command.Command.executeUpdate(Command.java:267)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$15(JdbcActionComponent.scala:520)
at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:517)
at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingInsertInvoker.insert(BlockingProfile.scala:125)
at gitbucket.core.service.WebHookService.addWebHook(WebHookService.scala:124)
at gitbucket.core.service.WebHookService.addWebHook$(WebHookService.scala:116)
at gitbucket.core.controller.ApiController.addWebHook(ApiController.scala:10)
at gitbucket.core.controller.api.ApiRepositoryWebhookControllerBase.$anonfun$$init$$10(ApiRepositoryWebhookControllerBase.scala:36)
at scala.Option.map(Option.scala:242)
at gitbucket.core.controller.api.ApiRepositoryWebhookControllerBase.$anonfun$$init$$6(ApiRepositoryWebhookControllerBase.scala:32)
at gitbucket.core.util.WritableUsersAuthenticator.$anonfun$authenticate$9(Authenticator.scala:142)
at scala.Option.map(Option.scala:242)
at gitbucket.core.util.WritableUsersAuthenticator.authenticate(Authenticator.scala:140)
at gitbucket.core.util.WritableUsersAuthenticator.writableUsersOnly(Authenticator.scala:132)
at gitbucket.core.util.WritableUsersAuthenticator.writableUsersOnly$(Authenticator.scala:132)
at gitbucket.core.controller.ApiController.writableUsersOnly(ApiController.scala:10)
at gitbucket.core.controller.api.ApiRepositoryWebhookControllerBase.$anonfun$$init$$5(ApiRepositoryWebhookControllerBase.scala:30)
at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:282)
at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:276)
at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:180)
at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:35)
at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:35)
at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:250)
at scala.Option.flatMap(Option.scala:283)
at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:248)
at scala.collection.immutable.Stream.flatMap(Stream.scala:206)
at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:247)
at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:245)
at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:35)
at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
at org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2(CompositeScalatraFilter.scala:67)
at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2$adapted(CompositeScalatraFilter.scala:64)
at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
at gitbucket.core.servlet.CompositeScalatraFilter.process(CompositeScalatraFilter.scala:64)
at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:25)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:80)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
at scala.Option.getOrElse(Option.scala:201)
at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
at scala.Option.getOrElse(Option.scala:201)
at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
at org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at gitbucket.core.servlet.ApiAuthenticationFilter.doFilter(ApiAuthenticationFilter.scala:43)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:572)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:516)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by takezoe** [comment]
This issue has been fixed in 4.35.1 and now 4.35.2 is also available. Please try 4.35.2.

**Comment by solvingj** [comment]
Good news: It turns out this error was related to me trying to create a webhook when a webhook with the same name already existed on that repo. 

Bad news: It turns out the `create` hooks are still not happening when a branch is created.  

Good news: I've found that the problem only exists when creating the branch via the UI.  When actually pushing branch via GIT CLI, it does send the hook. I'll file separate bug for this issue, which has likely existed for a while.  All my previous testing was creating branches via the GIT CLI.

**Comment by takezoe** [comment]
> It turns out this error was related to me trying to create a webhook when a webhook with the same name already existed on that repo.

Registering multiple webhooks with the same URL isn't allowed in GitBucket.

> It turns out the create hooks are still not happening when a branch is created.
> the problem only exists when creating the branch via the UI.

Ah, I see. This needs to be improved. Could you create an issue for this?

**Comment by solvingj** [comment]
https://github.com/gitbucket/gitbucket/issues/2619

**Comment by takezoe** [comment]
Thank you!
