### ISSUE TITLE
Can't create pull request when branch names are longer than 100 chars.

### ISSUE THREAD

**Issue by XWolfOverride** [gitbucket/gitbucket#3665]
## Issue
**Impacted version**: 4.41.0

**Deployment mode**: *standalone app with nginx*

**Problem description**:
- When creating a branch with long names (we use User Story descriptions on branch names) creating a pull request of the branch raises an silent error, UI does show nothing but error is seen in browser console.
- Call top https://*****/pulls/new/validate returns HTTP 200 with body: {"requestBranch":"requestBranch cannot be longer than 100 characters."}
- On headers "requestBranch" is "BUGFIX-HOM-3819-en-el-popup-de-añadir-caregiver,-si-se-realiza-búsqueda-con-un-espacio,-recupera-todos-los-caregivers-" (more than 100 chars)

Is it possible to increase the limit?

**Comment by takezoe** [comment]
Hmm... I don't think 100 chars of branch names are not usual and I don't know how long branch names we should support in GitBucket. What is your expected upper limit? We can consider it if it's reasonable.

By the way, I fixed the pull request creation UI to show error messages for the length of branch names in #3667. Thank you for your feedback.

**Comment by XWolfOverride** [comment]
Hello, I think 100 chars for branch names ar not usual, but a side effect of our branching model, we split the work on user stories with a descriptive name and use the user story name as branch name, to locate the fetaure branch in one sight. I'm trying to reduce the long of a branch name, but sometimes it still get long.

For other side there are some git clients that organice the work in kind of branch foldres allowing char "/" to be set on branch names and interpreting it as a filename path and grouping coincindent "folders", as fas as I know is something github introduces not far ago, I think branch names will get larger as people start using it.

To say a limit not too high I like the 256 for that (I'm used to power of two numbers).

Thanks.

**Comment by takezoe** [comment]
Thanks. 256 sounds reasonable. We will consider it.
